version: "3.7"

services:
  postgres_raccoon_consultant:
    image: postgres:${PG_MAJOR}
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres-data:/var/lib/postgresql/data
      - ./log:/root/log:cached
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
      - POSTGRES_USER=${PG_USR}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USR} -d ${DATABASE_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env

  appserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: raccoon-consultant-app
    command: "java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -Dspring.profiles.active=postgres -jar /app/raccoon_consultant-0.0.1-SNAPSHOT.jar"
    depends_on:
      - postgres_raccoon_consultant
    expose:
      - ${WEB_APP_PORT}
    ports:
      - ${WEB_APP_PORT}:${WEB_APP_PORT}
    env_file:
      - .env

volumes:
  postgres-data:

networks:
  default:
    external:
      name: raccoon_default
